{{- $governanceEnabled := true }}
{{- if hasKey .Values "addons" }}
{{- if hasKey .Values.addons "governancePolicyFramework" }}
{{- $governanceEnabled = .Values.addons.governancePolicyFramework }}
{{- end }}
{{- end }}
{{- if $governanceEnabled }}
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: governance-policy-framework
  namespace: {{ .Values.namespace }}
spec:
  installNamespace: open-cluster-management-agent-addon
{{- end }}
{{- $configPolicyEnabled := true }}
{{- if hasKey .Values "addons" }}
{{- if hasKey .Values.addons "configPolicyController" }}
{{- $configPolicyEnabled = .Values.addons.configPolicyController }}
{{- end }}
{{- end }}
{{- if $configPolicyEnabled }}
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: config-policy-controller
  namespace: {{ .Values.namespace }}
spec:
  installNamespace: open-cluster-management-agent-addon
{{- end }}
{{- $hubTemplatingEnabled := false }}
{{- if hasKey .Values "addons" }}
{{- if hasKey .Values.addons "governanceStandaloneHubTemplating" }}
{{- $hubTemplatingEnabled = .Values.addons.governanceStandaloneHubTemplating }}
{{- end }}
{{- end }}
{{- if $hubTemplatingEnabled }}
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: governance-standalone-hub-templating
  namespace: {{ .Values.namespace }}
spec:
  installNamespace: open-cluster-management-agent-addon
{{- if .Values.addons.hubTemplatingSecretAccess }}
{{- range .Values.addons.hubTemplatingSecretAccess }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: governance-hub-templating-secret-reader
  namespace: {{ .namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "argocd.argoproj.io/sync-options": "Prune=false"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: governance-hub-templating-{{ $.Values.clusterName }}
  namespace: {{ .namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: governance-hub-templating-secret-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: "system:open-cluster-management:cluster:{{ $.Values.clusterName }}:addon:governance-standalone-hub-templating:agent:governance-standalone-hub-templating"
{{- end }}
{{- end }}
{{- end }}
