{{- range .Values.nodes }}
{{- if .bmcCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-bmc
  namespace: {{ $.Values.namespace }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-3"
type: Opaque
stringData:
  username: {{ .bmcCredentials.username | quote }}
  password: {{ .bmcCredentials.password | quote }}
{{- end }}
{{- end }}
