{{- if .Values.clusterManifests }}
{{- if gt (len .Values.clusterManifests) 0 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-manifests
  namespace: {{ .Values.namespace }}
{{- if .Values.commonLabels }}
  labels:
    {{- include "cluster.commonLabels" . | nindent 4 }}
{{- end }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-2"
data:
{{- range $filename, $content := .Values.clusterManifests }}
  {{ $filename }}: |
{{ $content | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
