{{- $hasManifests := and .Values.clusterManifests (gt (len .Values.clusterManifests) 0) }}
{{- $hasMTU := .Values.agentClusterInstall.networking.clusterNetworkMTU }}
{{- if or $hasManifests $hasMTU }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-manifests
  namespace: {{ .Values.namespace }}
{{- if .Values.commonLabels }}
  labels:
    {{- include "cluster.commonLabels" . | nindent 4 }}
{{- end }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-2"
data:
{{- range $filename, $content := .Values.clusterManifests }}
  {{ $filename }}: |
{{ $content | indent 4 }}
{{- end }}
{{- if $hasMTU }}
  99-cluster-network-mtu.yaml: |
    apiVersion: operator.openshift.io/v1
    kind: Network
    metadata:
      name: cluster
    spec:
      defaultNetwork:
        ovnKubernetesConfig:
          mtu: {{ .Values.agentClusterInstall.networking.clusterNetworkMTU }}
{{- end }}
{{- end }}
