{{- if .Values.clusterSet }}
{{- if ne (.Values.createClusterSet | default "true" | toString) "false" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: {{ .Values.clusterSet }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Prune=false
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
{{- end }}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: {{ .Values.clusterSet }}
  namespace: {{ .Values.namespace }}
spec:
  clusterSet: {{ .Values.clusterSet }}
{{- end }}
