---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.namespace }}
{{- if .Values.commonLabels }}
  labels:
    {{- include "cluster.commonLabels" . | nindent 4 }}
{{- end }}
spec:
  clusterRef:
    name: {{ .Values.clusterName }}
    namespace: {{ .Values.namespace }}
  pullSecretRef:
    name: pull-secret
  sshAuthorizedKey: {{ .Values.sshPublicKey | quote }}
{{- if .Values.infraEnv.kernelArguments }}
  kernelArguments:
{{- range .Values.infraEnv.kernelArguments }}
      - operation: {{ .operation }}
        value: {{ .value | quote }}
{{- end }}
{{- end }}
{{- if .Values.infraEnv.additionalNTPSources }}
  additionalNTPSources:
{{- range .Values.infraEnv.additionalNTPSources }}
    - {{ . | quote }}
{{- end }}
{{- end }}
  nmStateConfigLabelSelector:
    matchLabels:
      infraenvs.agent-install.openshift.io: {{ .Values.clusterName | quote }}
