---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
{{- if .Values.commonLabels }}
  labels:
    {{- include "cluster.commonLabels" . | nindent 4 }}
{{- end }}
  annotations:
{{- if eq (.Values.namespaceResourcePolicy | default "keep") "keep" }}
    "helm.sh/resource-policy": keep
    "argocd.argoproj.io/sync-options": "Prune=false"
{{- end }}
    "argocd.argoproj.io/sync-wave": "-5"
