---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: {{ .Values.namespace }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-4"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret.dockerconfigjson | quote }}
