---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: {{ .Values.namespace }}
{{- if .Values.commonLabels }}
  labels:
    {{- include "cluster.commonLabels" . | nindent 4 }}
{{- end }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-4"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret.dockerconfigjson | quote }}
